version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=bsf
      - POSTGRES_USER=bsf
      - POSTGRES_PASSWORD=bsf
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=bsf
      - POSTGRES_USER=bsf
      - POSTGRES_PASSWORD=bsf
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
